### ISSUE TITLE
Getting Array to string conversion error on Php 7

### ISSUE THREAD

**Issue by frogydiak** [jmosmap/plugin_googlemaps#28]
On line# 293 of /plugins/system/plugin_googlemap3/plugin_googlemap3_helper.php:

`this->_mp->$values[0]`

causes Notice: Array to string conversion but if I modify the code to:

`
$key = $values[0];
$this->_mp->{$key} = $values[1];
`

the Notice goes away.

**Comment by dautrich** [comment]
I've successfully tested this patch both under PHP 5.6.x and PHP 7.0.x.
I propose to use the patch in the next release of Google Maps Plugin.

**Comment by coolcat-creations** [comment]
thanks that helped!

**Comment by dautrich** [comment]
You're welcome!

**Comment by thexmanxyz** [comment]
Fixed my width:100% overwrite issue too. Really thx!

**Comment by dautrich** [comment]
The issue has **not** been fixed in version 3.4 of the plugin. The line number to apply the patch has changed to line **301**.
With that patch, I have successfully tested the new plugin version under PHP7.

**Comment by thexmanxyz** [comment]
Can also confirm that applying the patch at line 301 in Version 3.4 does fix the problem again. 3.4 by default still contains the issue.

**Comment by abergo** [comment]
Try curly brackets. this->_mp->{$values[0]}

**Comment by gorgonz** [comment]
(first) fix works. Maybe it should be mentioned, that "if" doesn't have curly braces here, so
`this->_mp->$values[0]=$values[1];`
should be replaced with
`{ $key = $values[0]; $this->_mp->{$key} = $values[1]; }`

**Comment by thexmanxyz** [comment]
New Revision is out 3.5 (i think). But the problem still persists in 3.5 and has not been fixed. The proposed fix from above still works ;). Just to let you all know :P

**Comment by GeraldST** [comment]
I guess developer has left the building ... the two pending pull requests  #28 and #25 helped me a lot. Sadly they haven't got a commit for quite some time.

**Comment by dautrich** [comment]
It was Mike Reumer's extension, but for whatever reason he has left and handed over to somebody else. The new team (?) obviously tried to make some money for support services, but seems to lack the experience to run a project like this. It's a shame!
For me the extension was the very best map extension functionally, but the lack of support forced me to switch to Phoca Maps.

**Comment by Mushr0000m** [comment]
So the team will not give an update for that big issue ?

**Comment by dautrich** [comment]
The issue is pending for more than one year now. Any questions?

**Comment by thexmanxyz** [comment]
@dautrich I don't think there would be any support here in the future. The best way would be that someone forks the project and maintains it and at least trys to handle pull requests and bug reports. See also my issues #39 and #40

**Comment by dautrich** [comment]
@thexmanxyz I propose you do the job.
I'm only a user/webmaster, but lack experience in PHP.
