### ISSUE TITLE
Plugin Mod / Fork, Update and what happened

### ISSUE THREAD

**Issue by thexmanxyz** [jmosmap/plugin_googlemaps#40]
Hey there, I know many of you noticed that something strange happened to this plugin. There was over a long period no update and at the beginning of the year a new version was released and shared only over the website by a potential new owner. The old version which is available over this repo is still v3.3 and the version provided over the new "official" website (at least the domain changed) http://www.mapsplugin.com is v3.5. I did a rough diff over the files and there were a lot of changes between these two versions. But most of them look ok. However the changes were never updated here in the git repo (even after 8 months). That's mysterious. There is a popular fix for PHP 7 which also was not integrated even since it is known for at least a year #28 

Moreover @jaccsnl noticed strange lines in the code, possibly found during a Sucuri.net scan - see also #39. So I tried to find the problematic lines described by @jaccsnl by myself because he did not provide further infos. As already discussed in #39 the related code that I found seems to be a bit strange and very questionable. Moreover I noticed a bug in 'plugin_googlemap3.css.php' and a deprecated Google Maps JS Api query parameter "signed_in=0|1", which is still sent during requests. So I decided to fix these issues, remove the mysterious lines of code described in #39 and create a new version. For further information please review #39 I will not describe everything I discovered again.

So the new version is <del>3.5.1</del> [3.5.2](https://github.com/jmosmap/plugin_googlemaps/files/1331057/plugin_googlemaps-J25_J3x.v3.5.2.zip) and contains:
- fixes #28 / #30 / #36 for PHP7
- fixes #25 / #29 / #38 (force SSL - readonly already fixed in v3.5)
- fixes Maps JS API query parameter ("signed_in")
- fixes a bug introduced with one of the last joomla versions (factory.php lib moved to database subfolder), i corrected the path in 'plugin_googlemap3.css.php'
- the mysterious lines in 'plugin_googlemap3.php' were removed because they can be easily used to reload malicious code and i personally do not trust them (#39)
- removed MOSX platform files

<del>Please give me some time to prepare the new version. I will come back here to further discuss these issues and provide you further information.</del> For more infos see the next post.

**Comment by thexmanxyz** [comment]
So finally the updated version **v3.5.2** of the plugin with the above described fixes is here. I know that this is far from the best way to provide an update but currently I do not know a better or faster way to offer a distribution of the updated version of the plugin. I strongly recommend everyone who still uses this plugin to download this version and install it. However please consider the problematic situation around this plugin, I'm not responsible for anything...it's just a fix to circumvent the possibility to inject code over this potential "backdoor" as long as the owner does not communicate what these lines actually do and for what they are used. I personally doubt that these lines make any sense other than pushing some stuff on the webserver of a person using this plugin. Why load a credit from the server and not hard code it? It's stupid because if a person understands PHP code it doesn't makes it more difficult to remove the credit. That's the only comprehensible thing I can think about and this doesn't makes any sense either.

Everything is just an assumption by me, but as long as there is no official communciation or statement by the owner (other than the updates without any changelogs) on the "official" site, it's better to take care. <del>Moreover I have to invest a bit more time to get an overview between the v3.3, v3,4 and v3.5 and the fake version(s) of the plugin because something is messed up in the whole version management and the overtaking of the plugin...</del> I now fully reviewed the file and code changes from v3.3 - v3.5 and except the lines described in #39 there is nothing suspicious in the code as far as i can tell but I invite everyone to also do a review of the code. Especially the plugin and kml JS code obfuscated by minification...

Feel free to verify my archive and the code I uploaded. But there are no differences except the fixes described above. Moreover I hope that someone joins the discussion. I'm looking forward for some community input. The base for v3.5.2 was the version v3.5 taken from [http://www.mapsplugin.com/update/](http://www.mapsplugin.com/update/). For the moment this version should work. In the near future I will create a fork of this repo because the current situation is far from acceptable. I don't have deep knowledge of the Maps API so I hope on participation :D.

[plugin_googlemaps-J25_J3x.v3.5.2.zip](https://github.com/jmosmap/plugin_googlemaps/files/1331057/plugin_googlemaps-J25_J3x.v3.5.2.zip)

**Comment by ballaballa123** [comment]
Thanks a lot.

**Comment by thexmanxyz** [comment]
@ballaballa123 np

**Comment by ypr52** [comment]
I have been using 3.5.2 for a while and find no problems. Thank you for all your hard work.

**Comment by thexmanxyz** [comment]
@ypr52 glad to hear, np :)

**Comment by ypr52** [comment]
I have a question. The 3.5.2 plugin works fine on a live site but when using it on a test site (using XAMPP v3.2.2) it does not always load (I sometimes get a location in Holland). Do you know the reason for this?

**Comment by thexmanxyz** [comment]
@ypr52 TBH I can't really say what's the actual issue, never noticed it on one of my test sites. Open please a new issue maybe someone else has a solution. It would be better recognizable by other people within an separate issue. If there is a solution I will integrate it and create a new release.

**Comment by grantiago** [comment]
@thexmanxyz -- Five years late. Thank you. I've been using this for 3.5.2 without problems. It is, still, five years later, the only viable maps plugin for joomla. Does pretty much everything: kml, directions, sidebar, etc.. The important feature is it _works_ in categories, articles, modules. It will **display multiple instances** of the map on one page! Rain, snow or sleet. 

It would be great if someone could fork this 😉  and keep it going. I am here commenting as I was trying to mod another map plugin and I just don't have the coding skills with joomla. I dropped by to snoop around the code for some insight and felt the need to comment. 🍺  👍

**Comment by rgtr** [comment]
Hi
I created a plugin which ONLY shows a KML based map ...
It is on JED under the name TDOCGmap - so called as my own software is called "TDOC"
See here for more http://tdocplus.co.uk/0a_Empty400/kml-map
It has now been modified and translated into Spanish ... but the modifier just advised that some bugs have arisen
See here: : https://github.com/grantiago/tdocgmap
Enjoy !

**Comment by grantiago** [comment]
hi. had to look up some of the myriad of options. Since Mike's site is gone, here is the way back machine copy:
[options](http://web.archive.org/web/20160302031233/http://www.mapsplugin.com/Google-Maps/Documentation-of-plugin-Googlemap/parameters-of-plugin-google-maps.html)

**Comment by lostincoding** [comment]
> So finally the updated version **v3.5.2** of the plugin with the above described fixes is here. I know that this is far from the best way to provide an update but currently I do not know a better or faster way to offer a distribution of the updated version of the plugin. I strongly recommend everyone who still uses this plugin to download this version and install it. However please consider the problematic situation around this plugin, I'm not responsible for anything...it's just a fix to circumvent the possibility to inject code over this potential "backdoor" as long as the owner does not communicate what these lines actually do and for what they are used. I personally doubt that these lines make any sense other than pushing some stuff on the webserver of a person using this plugin. Why load a credit from the server and not hard code it? It's stupid because if a person understands PHP code it doesn't makes it more difficult to remove the credit. That's the only comprehensible thing I can think about and this doesn't makes any sense either.
> 
> Everything is just an assumption by me, but as long as there is no official communciation or statement by the owner (other than the updates without any changelogs) on the "official" site, it's better to take care. ~Moreover I have to invest a bit more time to get an overview between the v3.3, v3,4 and v3.5 and the fake version(s) of the plugin because something is messed up in the whole version management and the overtaking of the plugin...~ I now fully reviewed the file and code changes from v3.3 - v3.5 and except the lines described in #39 there is nothing suspicious in the code as far as i can tell but I invite everyone to also do a review of the code. Especially the plugin and kml JS code obfuscated by minification...
> 
> Feel free to verify my archive and the code I uploaded. But there are no differences except the fixes described above. Moreover I hope that someone joins the discussion. I'm looking forward for some community input. The base for v3.5.2 was the version v3.5 taken from http://www.mapsplugin.com/update/. For the moment this version should work. In the near future I will create a fork of this repo because the current situation is far from acceptable. I don't have deep knowledge of the Maps API so I hope on participation :D.
> 
> [plugin_googlemaps-J25_J3x.v3.5.2.zip](https://github.com/jmosmap/plugin_googlemaps/files/1331057/plugin_googlemaps-J25_J3x.v3.5.2.zip)

Hey there @thexmanxyz :)

I've read everything in this thread. Is 3.5.2 the latest version of the plugin?
I have an old website running Joomla3, where I'm doing some maintenance. I just updated Joomla to the latest version 3.10.12. The update itself went fine.

But I noticed the map is not loading correctly in the Contacts page, even though I added an API Key in the plugin settings. I don't think it's related to the fact that I updated the site. The map was probably dead for a while but because this is a low traffic site, no one noticed/complained. I didn't even know which plugin was being used, it took me a while to understand what's happening.

Since I have my hands on it, I'm curious if I can fix this and get a working map.
Current version says:
> system / plugin_googlemap2
> Plugin Googlemap - A Joomla plugin
> This is version 2.18 of the plugin Google maps for Joomla 1.5+ native, Joomla 2.5+ and Joomla 3.0+ and support for Google Maps API version 2 and 3 (Google Terms).

How would I proceed to update the plugin? Delete everything inside the folder **_media/plugin_googlemap2_** and upload contents from your zip file in there?

I appreciate your help on this. Thank you!

**Comment by thexmanxyz** [comment]
@lostincoding Hey, the 3.5.2 is a custom version of the last official version of the plugin. What has been fixed in 3.5.2 can be found in the comments of the issue. There were no changes except the ones I described above. The version I created is working since years flawlessly on J3 and I did not experience any issues for my use case. I did of course not test all possible configurations of the plugin. The plugin still works fine with the latest J3 version namely 3.10.12. 

You can install the above attached zip file via the Joomla plugin installation by uploading the zip to your web server and pointing to the install file. I would do it like that and without removing anything manually from the web server. Of course be sure that this is the same plugin. I'm not on PC and can't check whether it really is. But you should be able to determine with the existing J3 install, the zip file and the folders on the web servers.

Before breaking something permanently I would recommend to test it in some staging environment or make a full backup of web server / db in case you don't have a staging. Simply that you can roll back if something goes terribly wrong. However the risk is rather small I would say.

Proceed with my suggestions and in case it did not work provide details about the current version of the plugin and a debug output from Joomla in case it's not working with 3.5.2. Any feedback positive or negative of course welcome 🙂.

**Comment by thexmanxyz** [comment]
@lostincoding ah I overlooked that you wrote it's 2.18 of the plugin. I'm not sure if the 2.18 can be directly replaced by 3.5.2. Otherwise you might need to uninstall the old version and reconfigure 3.5.2.

**Comment by lostincoding** [comment]
> @lostincoding ah I overlooked that you wrote it's 2.18 of the plugin. I'm not sure if the 2.18 can be directly replaced by 3.5.2. Otherwise you might need to uninstall the old version and reconfigure 3.5.2.

Hi :)
Thanks for replying!

I'm not great with Joomla. I struggle a bit with some of its concepts (plugins, modules, articles).
This is the only Joomla website I ever worked with, the only reason I have it is because I inherited it from someone else. I do have experience with Drupal and Wordpress.

For example, I have looked everywhere but I still don't understand how the map is inserted in the Contacts page.
I have checked in:
- Components > Contacts > Contacts > Contacts page (screenshot: https://i.imgur.com/4pd6LUA.png )
- Extensions > Modules (I dont see anything related to Maps here - screenshot: https://i.imgur.com/WvJi7Ih.png )
- Extensions > Plugins > Google Maps (screenshot: https://i.imgur.com/qlip5fG.png )
- Content > Articles (I dont see anything related to Contacts here - screenshot: https://i.imgur.com/lfhGD4L.png )

I know the map is being inserted somehow because it's showing with an error in the front, as well as in the javascript console. Screenshot: https://i.imgur.com/RwWg6KS.png .

So I have a couple of questions:

1) Is there a place I can look at for some guidance on how to properly setup the plugin and make changes if needed? I understand the official website of the original developer (Mike Reumer) is down. EDIT: There's install instructions [HERE](https://web.archive.org/web/20160213002502/http://www.mapsplugin.com/Google-Maps/Documentation-of-plugin-Googlemap/tutorial-installuse.html) but the example given is for a new article and in my case the map is in the Contacts page, so I'm still stuck in my understanding of how this works.

2) Let's assume I want to uninstall the existing version of the plugin. How do I properly do that? Is it under Extensions > Manage > Manage ? (screenshot: https://i.imgur.com/TEjdmKf.png )

EDIT: reformulated the last part of my comment, for clarity.
